import jsPDF from "jspdf";

interface Activity {
  time: string;
  activity: string;
  location: string;
  cost: string;
}

interface Day {
  day: number;
  title: string;
  activities: Activity[];
}

interface Itinerary {
  title: string;
  destination: string;
  duration: string;
  budget: string;
  summary: string;
  days: Day[];
  tips: string[];
  totalEstimatedCost: string;
}

export function generateItineraryPDF(itinerary: Itinerary) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const checkPageBreak = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
  };

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(217, 119, 39); // primary orange
  doc.text(itinerary.title, margin, y);
  y += 10;

  // Subtitle info
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`${itinerary.duration}  •  Budget: ${itinerary.budget}  •  Est. Cost: ${itinerary.totalEstimatedCost}`, margin, y);
  y += 8;

  // Summary
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  const summaryLines = doc.splitTextToSize(itinerary.summary, contentWidth);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 5 + 8;

  // Divider
  doc.setDrawColor(230, 230, 230);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Days
  itinerary.days.forEach((day) => {
    checkPageBreak(30);

    // Day header
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(217, 119, 39);
    doc.text(day.title, margin, y);
    y += 8;

    day.activities.forEach((act) => {
      checkPageBreak(18);

      // Time
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(217, 119, 39);
      doc.text(act.time, margin, y);

      // Activity
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      const actLines = doc.splitTextToSize(act.activity, contentWidth - 30);
      doc.text(actLines, margin + 28, y);
      y += actLines.length * 4.5;

      // Location + Cost
      doc.setFontSize(8);
      doc.setTextColor(130, 130, 130);
      const meta = `📍 ${act.location}${act.cost && act.cost !== "₹0" ? `  •  ${act.cost}` : ""}`;
      doc.text(meta, margin + 28, y);
      y += 7;
    });

    y += 4;
  });

  // Tips
  if (itinerary.tips && itinerary.tips.length > 0) {
    checkPageBreak(20);
    doc.setDrawColor(230, 230, 230);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(217, 119, 39);
    doc.text("💡 Travel Tips", margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);

    itinerary.tips.forEach((tip) => {
      checkPageBreak(10);
      const tipLines = doc.splitTextToSize(`• ${tip}`, contentWidth);
      doc.text(tipLines, margin, y);
      y += tipLines.length * 5 + 2;
    });
  }

  // Footer
  checkPageBreak(20);
  y += 5;
  doc.setDrawColor(230, 230, 230);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text("Generated by Where Is My Trip • whereismytrip.in • +91 9082494524", margin, y);

  doc.save(`${itinerary.destination.replace(/\s+/g, "-")}-itinerary.pdf`);
}
